### PR TITLE
Branch 1.2(added leaderboard)

### PR DESCRIPTION
**Pull request by blank-27**

### CODE REVIEW

**Comment by dojutsu-user** [comment]
Please do separate PRs if your solving different things.

**Comment by dojutsu-user** [comment]
@blank-27 
This PR is not correct.
Please do a separate PR if you are solving multiple PRs.
See other merged PRs for example.

**Comment by dojutsu-user** [comment]
Please update your PR.

**Comment by rishabhshuklax** [comment]
Create a separate PR for this from the new branch and also open the issue for leaderboard button then make PR referencing that issue, for now, I am closing this.

**Pull request closed without merging**
