### PR TITLE
Branch 1.6(solved the issue #7)

### PR DESCRIPTION
**Pull request by blank-27**

### CODE REVIEW

**Comment by dojutsu-user** [comment]
@blank-27 
Please resolve the merge conflicts.

**Comment by dojutsu-user** [comment]
Please provide a screenshot of the changes done and the issue this PR is solving.

**Comment by blank-27** [comment]
sir, I had uploaded the screenshots in the comments section of issue
#7(which is already assigned to me)
issue---Fix landing page image. #7
my github username-blank-27

**Comment by dojutsu-user** [comment]
@blank-27 
Is this PR related to #7 or a duplicate of #7?

**Comment by dojutsu-user** [comment]
Please don't make separate PRs for same issue. Work on a same PR.
If this is a duplicate PR, please close this and work on the original PR.

**Pull request merged**
