### PR TITLE
Remove space

### PR DESCRIPTION
**Pull request by 0cirius0**

### CODE REVIEW

**Comment by rishabhshuklax** [comment]
Which issue does this solve?

**Comment by 0cirius0** [comment]
issue: fix the landing page image

**Comment by rishabhshuklax** [comment]
issue number?

**Comment by 0cirius0** [comment]
Issue #6

**Comment by rishabhshuklax** [comment]
Don't replace span with div and remove the bottom padding instead of giving margin-bottom.

**Comment by rishabhshuklax** [comment]
@hellrider9 what's the status? Are you still working on this?

**Comment by 0cirius0** [comment]
No i am not working on this.
But i would like to know how it is done

**Pull request closed without merging**
